# Generated by Django 5.2.5 on 2026-02-27 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_productos_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estrategiafidelizacion',
            name='codigos_para_beneficio',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='BeneficioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('descuento_50', '50% de descuento'), ('regalo_misterioso', 'Regalo misterioso'), ('bebida_gratis', 'Bebida gratis')], max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('otorgado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.cliente')),
            ],
            options={
                'ordering': ['-otorgado_en'],
            },
        ),
        migrations.CreateModel(
            name='CodigoFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='core.cliente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
