# Generated by Django 6.0.2 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=12, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='menus_dia', to='core.producto')),
            ],
            options={
                'verbose_name': 'Menú por día',
                'verbose_name_plural': 'Menús por día',
                'ordering': ['dia_semana'],
            },
        ),
    ]
