# Generated by Django 6.0.2 on 2026-03-02 00:00

from django.db import migrations


def seed_10_productos_por_dia(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')
    Categoria = apps.get_model('core', 'Categoria')
    MenuDia = apps.get_model('core', 'MenuDia')

    dias = [
        ('lunes', 'Lunes'),
        ('martes', 'Martes'),
        ('miercoles', 'Miercoles'),
        ('jueves', 'Jueves'),
        ('viernes', 'Viernes'),
        ('sabado', 'Sabado'),
        ('domingo', 'Domingo'),
    ]

    categoria_menu, _ = Categoria.objects.get_or_create(nombre='Menu diario')

    for dia_slug, dia_nombre in dias:
        menu, _ = MenuDia.objects.get_or_create(dia_semana=dia_slug, defaults={'activa': True})
        menu.activa = True
        menu.save()

        productos_dia = []
        for numero in range(1, 11):
            nombre_producto = f'{dia_nombre} - Plato {numero}'
            producto, _ = Producto.objects.get_or_create(
                nombre=nombre_producto,
                defaults={
                    'categoria': categoria_menu,
                    'descripcion': f'Especial del {dia_nombre} número {numero}.',
                    'precio': str(15000 + (numero * 1000)),
                    'disponible': True,
                },
            )

            if not producto.categoria_id:
                producto.categoria = categoria_menu
                producto.save(update_fields=['categoria'])

            if not producto.disponible:
                producto.disponible = True
                producto.save(update_fields=['disponible'])

            productos_dia.append(producto)

        menu.productos.add(*productos_dia)


def reverse_seed_10_productos_por_dia(apps, schema_editor):
    # No se elimina información para evitar pérdida de datos cargados por el usuario.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menudia'),
    ]

    operations = [
        migrations.RunPython(seed_10_productos_por_dia, reverse_seed_10_productos_por_dia),
    ]
