# Generated by Django 6.0.2 on 2026-03-02 00:00

from django.db import migrations


def mejorar_descripcion_platos(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')

    proteinas = ['pollo a la plancha', 'carne asada', 'cerdo en salsa', 'pescado apanado']
    acompanamientos = ['arroz blanco', 'papas a la francesa', 'puré de papa', 'arroz con verduras']
    bebidas = ['limonada natural', 'jugo del día', 'té frío', 'agua saborizada']

    for producto in Producto.objects.filter(nombre__contains=' - Plato '):
        try:
            numero = int(producto.nombre.split('Plato ')[1])
        except (ValueError, IndexError):
            numero = 1

        proteina = proteinas[(numero - 1) % len(proteinas)]
        acompanamiento = acompanamientos[(numero - 1) % len(acompanamientos)]
        bebida = bebidas[(numero - 1) % len(bebidas)]

        producto.descripcion = (
            f'Incluye {proteina}, {acompanamiento}, ensalada fresca y {bebida}.'
        )
        producto.save(update_fields=['descripcion'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_10_productos_por_dia'),
    ]

    operations = [
        migrations.RunPython(mejorar_descripcion_platos, reverse_noop),
    ]
