# Generated by Django 6.0.2 on 2026-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_beneficiocliente_descuento_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiocliente',
            name='tipo',
            field=models.CharField(choices=[('descuento_virtual', 'Descuento virtual'), ('descuento_50', '50% de descuento'), ('regalo_misterioso', 'Regalo misterioso'), ('bebida_gratis', 'Bebida gratis')], max_length=20),
        ),
    ]
